name: docs
on:
  push:
    branches:
      - master
    paths:
      - doc/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: master
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
          cd $GITHUB_WORKSPACE/master/doc
          pip install -r requirements.txt
          mkdocs gh-deploy --force --remote-branch gh-pages
